### PR TITLE
[RSPEED-184] Rename upstream project to reflect the RPM naming

### PR DESCRIPTION
**Pull request by r0x0d**
This patch is intended to rename all references from the previous `shellai` naming to `Command Line Assistant`.

### CODE REVIEW

**Comment by r0x0d** [comment]
The copr project looks correct. I think since this is a rename, packit is confusing because in the main branch the name is still shellai.

**Review by beav — APPROVED** [review]
looks very straightforward. ack

**Review by hosekadam — APPROVED** [review]

**Review by pr-watson — APPROVED** [review]

**Pull request merged**
